source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RMPScrollingMenuBarController_Example' do
  pod "RMPScrollingMenuBarController", :path => "../"
end

target 'RMPScrollingMenuBarController_Tests'  do
  pod "RMPScrollingMenuBarController", :path => "../"

  # Comment outed because maybe FBSnapshotTestCase isn't support Swift2.
  #pod 'FBSnapshotTestCase'
end

target 'RMPScrollingMenuBarController_Example2' do
  pod "RMPScrollingMenuBarController"
end
